#!/usr/bin/env python3
"""生成结构化 PDF 文档。"""

import argparse
from pathlib import Path
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.cidfonts import UnicodeCIDFont
from reportlab.pdfgen import canvas


def parse_args() -> argparse.Namespace:
    """解析命令行参数。"""
    parser = argparse.ArgumentParser(description="生成 PDF 文档")
    parser.add_argument("--title", required=True, help="文档标题")
    parser.add_argument("--body", required=True, help="正文内容，可包含换行")
    parser.add_argument("--output", default="/home/sandbox/output.pdf", help="输出文件路径")
    return parser.parse_args()


def split_lines(text: str) -> list[str]:
    """按空行与换行拆分为段落行。"""
    lines: list[str] = []
    for block in text.split("\n\n"):
        raw_lines = [line.strip() for line in block.splitlines() if line.strip()]
        if raw_lines:
            lines.extend(raw_lines)
            lines.append("")
    if lines and lines[-1] == "":
        lines.pop()
    return lines


def draw_pdf(title: str, body: str, output: Path) -> None:
    """绘制 PDF 内容并保存。"""
    output.parent.mkdir(parents=True, exist_ok=True)

    # 注册中文字体，避免中文乱码。
    pdfmetrics.registerFont(UnicodeCIDFont("STSong-Light"))

    doc = canvas.Canvas(str(output), pagesize=A4)
    width, height = A4

    # 封面标题。
    doc.setFont("STSong-Light", 24)
    doc.drawString(25 * mm, height - 40 * mm, title)

    # 副标题和分割线。
    doc.setFont("STSong-Light", 11)
    doc.drawString(25 * mm, height - 48 * mm, "Generated by pdf-maker skill")
    doc.line(25 * mm, height - 52 * mm, width - 25 * mm, height - 52 * mm)

    # 正文区域。
    y = height - 65 * mm
    doc.setFont("STSong-Light", 12)
    for line in split_lines(body):
        if y < 25 * mm:
            doc.showPage()
            doc.setFont("STSong-Light", 12)
            y = height - 25 * mm
        if line == "":
            y -= 6 * mm
            continue
        doc.drawString(25 * mm, y, line)
        y -= 7 * mm

    doc.save()


def main() -> None:
    """程序入口。"""
    args = parse_args()
    output = Path(args.output)
    draw_pdf(args.title, args.body, output)
    print(f"PDF 文件已生成: {output}", flush=True)


if __name__ == "__main__":
    main()
